{
  "name": "laminas/automatic-releases",
  "on": {
    "milestone": {
      "types": ["closed"]
    }
  },
  "jobs": {
    "release": {
      "name": "GIT tag, release & create merge-up PR",
      "runs-on": "ubuntu-18.04",
      "steps": [
        {
          "uses": "actions/checkout@master"
        },
        {
          "name": "Release",
          "uses": "docker://laminas/automatic-releases",
          "with": {
            "args": "laminas:automatic-releases:release"
          },
          "env": {
            "GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }}
          }
        },
        {
          "name": "Release",
          "uses": "docker://laminas/automatic-releases",
          "with": {
            "args": "laminas:automatic-releases:create-merge-up-pull-request"
          },
          "env": {
            "GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }}
          }
        }
      ]
    }
  }
}
